# Generated by Django 4.0.1 on 2022-05-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelagency',
            name='business_plan_copy',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='exchange_statment',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='investment_copy',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='license_copy',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='partnership_file',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='reference_letter_copy',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='registration_copy',
        ),
    ]
