# Generated by Django 3.2 on 2022-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='business_plan_copy',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='exchange_statment',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='investment_copy',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='license_copy',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='partnership_file',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='reference_letter_copy',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='registration_copy',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
