# Generated by Django 3.2.6 on 2022-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20220523_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagency',
            name='business_plan_copy',
            field=models.FileField(default=0, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='exchange_statment',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='investment_copy',
            field=models.FileField(default=0, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='license_copy',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='reference_letter_copy',
            field=models.FileField(default=0, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='registration_copy',
            field=models.FileField(default=0, upload_to='documents/%Y/%m/%d'),
        ),
    ]
