# Generated by Django 4.0.3 on 2022-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_travelagency_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagency',
            name='business_plan_copy',
            field=models.FileField(default=0, upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='investment_copy',
            field=models.FileField(default=0, upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='license_copy',
            field=models.FileField(blank=True, upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='reference_letter_copy',
            field=models.FileField(default=0, upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='registration_copy',
            field=models.FileField(default=0, upload_to='attachments/%Y/%m/%d/'),
        ),
    ]
