# Generated by Django 4.0.3 on 2022-04-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_travelagency_business_plan_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagency',
            name='exchange_statment',
            field=models.FileField(blank=True, upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='partnership_file',
            field=models.FileField(default=0, upload_to='attachments/%Y/%m/%d/'),
        ),
    ]
