# Generated by Django 4.0.3 on 2022-04-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_travelagency_reside_in_pakistan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagency',
            name='foreign_dealing',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='other_branch',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='reside_in_pakistan',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='No'),
        ),
    ]
