# Generated by Django 3.2.6 on 2022-06-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristguideform',
            name='end_Date',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='start_Date',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='training_Institute_Name',
        ),
    ]
