# Generated by Django 4.0.1 on 2022-05-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_alter_touristguideform_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristguideform',
            name='capital_investment_statement',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='reference_letter',
        ),
    ]
