# Generated by Django 3.2.6 on 2022-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_auto_20220608_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristguideform',
            name='capital_investment_statement',
            field=models.FileField(default=0, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='reference_letter',
            field=models.FileField(default=0, upload_to='documents/%Y/%m/%d'),
        ),
    ]
