# Generated by Django 3.2.6 on 2022-06-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0003_remove_touristguideform_capital_investment_statement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auditors',
        ),
        migrations.DeleteModel(
            name='staff',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='capital_invested',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='educational_qualifications',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='number_of_languages',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='residential_number',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='telegraphic_address',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='telephone_number',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='training',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='year_of_establishment',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='year_of_experiance',
        ),
    ]
