# Generated by Django 3.2.6 on 2022-06-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0003_auto_20220608_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristguideform',
            name='capital_investment_statement',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='reference_letter',
        ),
    ]
