# Generated by Django 3.2.6 on 2022-06-05 13:34

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0004_auto_20220605_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristguideform',
            name='bank_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='capital_invested',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='educational_qualifications',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='number_of_languages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='residential_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='residential_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='telegraphic_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='telephone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='terms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Whether any other activities are proposed to be undertaken? If so, in what fields?', 'Whether any other activities are proposed to be undertaken? If so, in what fields?'), ('Please state if you or your partner, if anyone have been convicted of an offence, if so please give details.', 'Please state if you or your partner, if anyone have been convicted of an offence, if so please give details.'), ('I/we hereby solemnly declare that all the particulars give above are correct', 'I/we hereby solemnly declare that all the particulars give above are correct'), ('I/we hereby solemnly declare that if a licence is granted to me/us, I/We will abide by the Travel Agencies Act, 1976 and the Rules made their under the terms of the licence granted to me/us, and the code of conduct.', 'I/we hereby solemnly declare that if a licence is granted to me/us, I/We will abide by the Travel Agencies Act, 1976 and the Rules made their under the terms of the licence granted to me/us, and the code of conduct.')], max_length=484, null=True),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='training',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='year_of_establishment',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='year_of_experiance',
            field=models.IntegerField(null=True),
        ),
    ]
