# Generated by Django 3.2.6 on 2022-06-09 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0005_auto_20220608_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristguideform',
            name='capital_investment_statement',
        ),
        migrations.RemoveField(
            model_name='touristguideform',
            name='reference_letter',
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='end_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='start_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='training_Institute_Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
