# Generated by Django 3.2.6 on 2022-06-07 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0005_auto_20220605_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristguideform',
            name='end_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='start_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='touristguideform',
            name='training_Institute_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='touristguideform',
            name='training',
            field=models.BooleanField(default=False),
        ),
    ]
