# Generated by Django 3.2 on 2022-05-01 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('establishment_year', models.DateField(default=datetime.date.today)),
                ('commision_date', models.DateField(default=datetime.date.today)),
                ('telex_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('hotel_address', models.CharField(max_length=100)),
                ('telegraphic_address', models.CharField(max_length=100)),
            ],
        ),
    ]
