# Generated by Django 3.2 on 2022-05-07 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, null=True)),
                ('establishment_year', models.DateField(default=datetime.date.today, null=True)),
                ('commision_date', models.DateField(default=datetime.date.today, null=True)),
                ('telex_number', models.IntegerField(null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('hotel_address', models.CharField(max_length=100, null=True)),
                ('telegraphic_address', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('hotel_area', models.IntegerField(null=True)),
                ('covered_area', models.IntegerField(null=True)),
                ('area_type', models.CharField(max_length=100, null=True)),
                ('land_cost', models.IntegerField(null=True)),
                ('building_cost', models.IntegerField(null=True)),
                ('furniture_cost', models.IntegerField(null=True)),
                ('equipment_cost', models.IntegerField(null=True)),
                ('working_capital', models.IntegerField(null=True)),
                ('total_investment', models.IntegerField(null=True)),
            ],
        ),
    ]
