# Generated by Django 4.0.1 on 2022-05-09 00:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonBathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_no', models.CharField(blank=True, max_length=10, null=True)),
                ('bathroom_floor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonToilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet_no', models.CharField(blank=True, max_length=10, null=True)),
                ('toilet_floor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='area_of_compound',
            field=models.CharField(default=2343, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='area_of_garden',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='building_files',
            field=models.FileField(blank=True, null=True, upload_to='building_files/'),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='car_park',
            field=models.CharField(default=32, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='cloak_room_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='cloak_room_detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='construction_completion_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='floor_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='lifts_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='reading_room_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='reading_room_detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='reception_hall_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='reception_hall_detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='renovation_last_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='restaurant_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='restaurant_detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='restaurant_detail_files',
            field=models.FileField(null=True, upload_to='restaurant_files/'),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='restaurant_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='room_nature',
            field=models.CharField(choices=[('single bed room', 'SINGLE BED ROOM'), ('double bed room', 'DOUBLE BED ROOM'), ('suite room', 'SUITE ROOM')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='room_numbers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='staircase_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='visitor_room_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='visitor_room_detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30, null=True)),
                ('owner_ratio', models.CharField(max_length=30, null=True)),
                ('owner_full_address', models.CharField(max_length=200, null=True)),
                ('owner_telegraphic_address', models.CharField(max_length=200, null=True)),
                ('owner_telephone', models.CharField(max_length=15, null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelregistration')),
            ],
        ),
        migrations.CreateModel(
            name='HotelManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=30, null=True)),
                ('manager_ratio', models.CharField(max_length=30, null=True)),
                ('manager_full_address', models.CharField(max_length=200, null=True)),
                ('manager_telegraphic_address', models.CharField(max_length=200, null=True)),
                ('manager_telephone', models.CharField(max_length=15, null=True)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms_type', models.CharField(max_length=100, null=True)),
                ('rooms_type', models.CharField(max_length=100, null=True)),
                ('corridors_type', models.CharField(max_length=100, null=True)),
                ('attached_bathroom_type', models.CharField(max_length=100, null=True)),
                ('bathrooms_type', models.CharField(max_length=100, null=True)),
                ('toilets_type', models.CharField(max_length=100, null=True)),
                ('cuisine_name', models.CharField(max_length=100, null=True)),
                ('furniture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelregistration')),
            ],
        ),
    ]
