# Generated by Django 3.2 on 2022-05-06 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelregistration',
            name='commision_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='establishment_year',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='hotel_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='telegraphic_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelregistration',
            name='telex_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='hotel_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
