# Generated by Django 4.0.1 on 2022-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_commonbathroom_commontoilet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelregistration',
            name='building_files',
            field=models.FileField(blank=True, default=3243, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='restaurant_detail_files',
            field=models.FileField(blank=True, default=324, upload_to=''),
            preserve_default=False,
        ),
    ]
