# Generated by Django 3.2 on 2022-05-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotelregistration_building_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelregistration',
            name='building_files',
            field=models.FileField(blank=True, null=True, upload_to='building_files/'),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='floor_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='restaurant_detail_files',
            field=models.FileField(null=True, upload_to='restaurant_files/'),
        ),
        migrations.AlterField(
            model_name='hotelregistration',
            name='room_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
