# Generated by Django 4.0.1 on 2022-04-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0004_restraunt_address_restraunt_commission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restraunt',
            name='address',
            field=models.TextField(default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='telegraphic_num',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='telephone_num',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='telex_num',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
