# Generated by Django 4.0.1 on 2022-04-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0005_alter_restraunt_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restraunt',
            name='commission_date',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='establisment_date',
        ),
    ]
