# Generated by Django 4.0.1 on 2022-04-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0007_remove_restraunt_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restraunt',
            name='restraunt_name',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='telex_num',
        ),
    ]
