# Generated by Django 4.0.1 on 2022-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0008_remove_restraunt_restraunt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='restraunt_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
