# Generated by Django 4.0.1 on 2022-04-25 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0009_restraunt_restraunt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='establisment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
