# Generated by Django 3.2 on 2022-04-26 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0010_restraunt_establisment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='commission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='telex_num',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
