# Generated by Django 3.2 on 2022-04-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0012_auto_20220426_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='area_of_dining',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='area_of_kitchen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='ownership',
            field=models.CharField(choices=[('proprietary', 'Proprietary'), ('partnership', 'Partnership'), ('private company', 'Private Company'), ('limited', 'Limited'), ('unlimited', 'Unlimited')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='province',
            field=models.CharField(choices=[('balochistan', 'BALOCHISTAN'), ('punjab', 'PUNJAB'), ('sindh', 'SINDH'), ('kpk', 'KPK'), ('fata', 'FATA')], default='green', max_length=100),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='seating_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='total_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='town',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
