# Generated by Django 3.2 on 2022-04-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0013_auto_20220426_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restraunt',
            name='area_of_dining',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='area_of_kitchen',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='ownership',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='province',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='seating_area',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='street',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='total_area',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='town',
        ),
    ]
