# Generated by Django 3.2 on 2022-04-26 09:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0015_auto_20220426_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='annual_rent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='apprentices',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='available_facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('reception', 'RECEPTION'), ('bill counter', 'BILL COUNTER'), ('telephone', 'TELEPHONE'), ('air-condition', 'AIR-CONDITION'), ('heating', 'HEATING'), ('cloak room', 'CLOAK ROOM'), ('toilet', 'TOILET'), ('car park', 'CAR PARK'), ('entertainment', 'ENTERTAINMENT')], max_length=95, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='cost_of_equipment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='english_knowing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='name_of_designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='nature_of_room',
            field=models.CharField(choices=[('single bed room', 'SINGLE BED ROOM'), ('double bed room', 'DOUBLE BED ROOM'), ('suite room', 'SUITE ROOM')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='not_professionally',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='number_of_floors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='number_of_room',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='professionally_trained',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='rates',
            field=models.CharField(choices=[('immeidiatly', 'IMMEIDIATLY'), ('after dinner', 'AFTER DINNER')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='total_investment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='total_number_bearers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='total_number_billers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='total_number_cooks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='total_number_mangers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='total_number_receptionists',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='type_of_cuisine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='working_capital',
            field=models.IntegerField(null=True),
        ),
    ]
