# Generated by Django 3.2 on 2022-05-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0016_auto_20220426_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restraunt',
            name='address',
            field=models.TextField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='restraunt_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='telegraphic_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='telephone_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='telex_num',
            field=models.IntegerField(default=1),
        ),
    ]
