# Generated by Django 3.2 on 2022-05-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0017_auto_20220501_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restraunt',
            name='restraunt_name',
        ),
    ]
