# Generated by Django 3.2 on 2022-05-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0018_remove_restraunt_restraunt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='restraunt_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
